version: '0.1.0.{build}'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build: nuget restore LXD

build:
    publish_nuget: true
    include_nuget_references: true

artifacts:
    - path: LXD/LXD.*.nupkg

deploy:
    provider: NuGet
    api_key:
        secure: iOYzFt4VurzWRwsRIwA4x2nCHzWfP3Y3re/8nnR2h+GTMbun6vyzvnqMpPKvwuwb
    artifacts: LXD/LXD.*.nupkg

test: off
